#!/bin/bash
#install scull0 scull1 scull2 scull3 in /dev/
module="scull"
device="scull"
mode="664"

#install the module
#TODO not finished yet, need to check insmod manpage
insmod ./scull_module.ko || exit 1

#remove stale nodes
rm -f /dev/${device}[0-3]

#get major number of installed module from /proc/devices
#TODO not finished yet, need to check format of /proc/devices
#use -v to set variable to got ${module} in awk script
major=awk '" " {print $1}' /proc/devices

#create node file
#TODO not finished yet
#I need to check mknod manpage to make sure the synctax
mknod /dev/${device}0 c ${major} 0
mknod /dev/${device}1 c ${major} 1
mknod /dev/${device}2 c ${major} 2
mknod /dev/${device}3 c ${major} 3

#give appropriate group/permissions,
#and change the group
#Not all the distribution have staff, some have "wheel" instead
group="staff"
#check /etc/group, to see and choose the group name
grep -q 'ˆstaff:' /etc/group || group="wheel"
#change group
chgrp ${group} /dev/${device}[0-3]
chmod ${mode} /dev/${device}[0-3]

